[package]

name = "syncbox"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
log = "0.3.0"

[dev-dependencies]
env_logger = "0.3.0"
time       = "0.1.21"

[[test]]

name = "test"
path = "test/test.rs"
