[package]

name = "syncbox"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
log = "0.2.3"

[dev-dependencies]
env_logger = "0.2.2"
time       = "0.1.20"

[[test]]

name = "test"
path = "test/test.rs"
